In [41]:
import torch
import torch.nn as nn
import math

In [ ]:
# 1. The "Forward Pass"The Concept: A neural network is just a series of mathematical operations. In PyTorch, everything starts with a Tensor (like a fancy NumPy array).The Question: Create two tensors, $X$ (input) and $W$ (weights). 
# Perform a dot product and add a bias $b$ to get an output $Y$.Practical Goal: Can you manually compute $Y = X \cdot W + b$ using PyTorch functions?Pythonimport torch

# # Your Task:
# X = torch.tensor([2.0, 3.0])
# W = torch.randn(2, 1, requires_grad=True) # Random weights
# b = torch.randn(1, requires_grad=True)    # Random bias

# # TODO: Compute Y_pred
# # Y_pred = ...

# Your Task:
X = torch.tensor([2.0, 3.0])
W = torch.randn(2, 1, requires_grad=True) # Random weights
b = torch.randn(1, requires_grad=True)    # Random bias

print('X is :', X, X.shape)
print('W is', W, W.shape)
print('b is ', b, b.shape)

model = nn.Linear(in_features=2, out_features = 1)


W_input = model.weight.T
b_bias = model.bias

y_pred = X @ W_input + b_bias
print(y_pred)


# X is : tensor([2., 3.]) torch.Size([2])
# W is tensor([[0.4778],
#         [1.0373]], requires_grad=True) torch.Size([2, 1])
# b is  tensor([0.6885], requires_grad=True) torch.Size([1])
# tensor([0.4547], grad_fn=<AddBackward0>)

X is : tensor([2., 3.]) torch.Size([2])
W is tensor([[0.4778],
        [1.0373]], requires_grad=True) torch.Size([2, 1])
b is  tensor([0.6885], requires_grad=True) torch.Size([1])
tensor([0.4547], grad_fn=<AddBackward0>)


In [ ]:
# 2: The Loss Function (MSE)Now that you have a prediction (y_pred), we need to know how "bad" it is. In regression tasks (predicting numbers), we commonly use Mean Squared Error 
# Task:Define a "ground truth" tensor: y_true = torch.tensor([-5.0]).
# Calculate the loss manually using the formula: (y_pred - y_true)**2.
# Calculate the loss using PyTorch's built-in function: criterion = nn.MSELoss().
# Print both and see if they match. 

print(y_pred)
y_true = torch.tensor([-5.0])
mean_squared_error = (y_true - y_pred)**2
print(mean_squared_error)

criterion = nn.MSELoss()
nn_mean_squared_error =  criterion(y_true, y_pred)

print(math.isclose(mean_squared_error,nn_mean_squared_error))

# tensor([0.4547], grad_fn=<AddBackward0>)
# tensor([29.7543], grad_fn=<PowBackward0>)
# True

tensor([0.4547], grad_fn=<AddBackward0>)
tensor([29.7543], grad_fn=<PowBackward0>)
True


C:\Users\Sumed\AppData\Local\Temp\ipykernel_36104\41289340.py:15: UserWarning: Converting a tensor with requires_grad=True to a scalar may lead to unexpected behavior.
Consider using tensor.detach() first. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\autograd\generated\python_variable_methods.cpp:837.)
  print(math.isclose(mean_squared_error,nn_mean_squared_error))


In [ ]:
# 3: The "Backward Pass" (Autograd)
# This is where the "learning" actually begins. We have the error (Loss), but we need to know: "If I change my weights slightly, how much will the error change?"

# The Concept: When you call .backward() on your loss, PyTorch calculates the gradient (derivative) of the loss with respect to every tensor that has requires_grad=True.

# The Task:

# Using your mean_squared_error from Question 2, call mean_squared_error.backward().

# Print the gradients of the model's weights: print(model.weight.grad).

# Print the gradients of the model's bias: print(model.bias.grad).

print(y_true,  y_pred)
mean_squared_error.backward()
print(model.weight.grad)
print(model.bias.grad)

# tensor([-5.]) tensor([0.4547], grad_fn=<AddBackward0>)
# tensor([[21.8190, 32.7285]])
# tensor([10.9095])

tensor([-5.]) tensor([0.4547], grad_fn=<AddBackward0>)
tensor([[21.8190, 32.7285]])
tensor([10.9095])


In [ ]:
# 4: Gradient Descent (The Update)Now that we have the "slopes" (gradients), we need to actually change the weights. 
# If we don't change the weights, the model never learns.The Concept: We use an Optimizer. 
# The most basic one is Stochastic Gradient Descent (SGD). It performs the math:$W_{new} = W_{old} - (\text{Learning Rate} \times \text{Gradient})$
# The Task: Define an optimizer: optimizer = torch.optim.SGD(model.parameters(), lr=0.01).
# Print the current weights: print(model.weight).
# Step the optimizer: optimizer.step().
# Print the weights again: print(model.weight).


optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)
print(model.weight)
optimizer.step()
print(model.weight)

# Parameter containing:
# tensor([[ 0.4963, -0.2607]], requires_grad=True)
# Parameter containing:
# tensor([[ 0.2781, -0.5880]], requires_grad=True)

Parameter containing:
tensor([[ 0.4963, -0.2607]], requires_grad=True)
Parameter containing:
tensor([[ 0.2781, -0.5880]], requires_grad=True)


In [1]:
# 5: The Full Training Loop (The Final Boss)
# Now, we put all the pieces together. In a real project, you don't just update the weights once; you repeat the process until the model is accurate.

# The Task:
# Write a loop that runs 20 times. Inside the loop, you must perform the 5 essential steps of the training heartbeat:

# optimizer.zero_grad(): This is vital! PyTorch accumulates gradients by default. If you don't zero them out, the new gradients will be added to the old ones, and your model will spiral out of control.

# Forward Pass: Get a new prediction from the model.

# Loss Calculation: Compare that prediction to y_true.

# Backward Pass: Calculate the new gradients.

# Optimizer Step: Update the weights.
import torch
import torch.nn as nn


X = torch.tensor([2.0, 3.0])
W = torch.randn(2, 1, requires_grad=True) # Random weights
b = torch.randn(1, requires_grad=True)    # Random bias
y_true = torch.tensor([-5.0])

model = nn.Linear(in_features=2, out_features = 1)
y_pred = model(X)

criterion = nn.MSELoss()
nn_mean_squared_error = criterion(y_pred, y_true)

print('X is: ', X)
print('W is: ', W)
print('b is: ', b)
print('y_true is: '                          , y_true)
print('initial value of y_pred: '            , y_pred)
print('initial value of mean_squared_error: ', nn_mean_squared_error)

print('\n')
print('initial model weights: '              , model.weight)
print('\n')
print('initial model bias: '                 , model.bias)

# nn_mean_squared_error.backward()
# print(model.weight.grad)
# print(model.bias.grad)

print('\n')
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

print('-------running loop below-------')

for epoch in range(1,21):
    optimizer.zero_grad()
    y_pred = model(X)
    print('value of y_pred: ', y_pred)
    nn_mean_squared_error = criterion(y_true, y_pred)
    nn_mean_squared_error.backward()
    optimizer.step()
    print('new model weights: ', model.weight)

    if epoch%5==0:
        print('epoch number: ', epoch)
        print('loss: ', y_true - y_pred)
        print('mean squared error: ', nn_mean_squared_error)
        print('\n')


X is:  tensor([2., 3.])
W is:  tensor([[-0.9133],
        [-0.5197]], requires_grad=True)
b is:  tensor([0.0705], requires_grad=True)
y_true is:  tensor([-5.])
initial value of y_pred:  tensor([0.7739], grad_fn=<ViewBackward0>)
initial value of mean_squared_error:  tensor(33.3376, grad_fn=<MseLossBackward0>)


initial model weights:  Parameter containing:
tensor([[-0.0290,  0.0696]], requires_grad=True)


initial model bias:  Parameter containing:
tensor([0.6231], requires_grad=True)


-------running loop below-------
value of y_pred:  tensor([0.7739], grad_fn=<ViewBackward0>)
new model weights:  Parameter containing:
tensor([[-0.2599, -0.2769]], requires_grad=True)
value of y_pred:  tensor([-0.8428], grad_fn=<ViewBackward0>)
new model weights:  Parameter containing:
tensor([[-0.4262, -0.5263]], requires_grad=True)
value of y_pred:  tensor([-2.0068], grad_fn=<ViewBackward0>)
new model weights:  Parameter containing:
tensor([[-0.5459, -0.7059]], requires_grad=True)
value of y_pred:  ten