In [16]:
# 6: Training on a "Mini-Batch"The Concept: In the real world, we don't train on one row of data at a time. 
# we use a "batch."The Task: 
# 1. Create a dataset X with 3 rows of data: [[1.0, 2.0], [2.0, 3.0], [3.0, 4.0]].
# 2. Create $Y_{true}$ with 3 targets: [[5.0], [8.0], [11.0]].
# 3. Train your nn.Linear(2, 1) model for 50 epochs.
# Practical Goal: Observe how nn.MSELoss automatically calculates the average error across all 3 rows.

#import necessary libraries 
import torch
from torch.nn import Linear, MSELoss
from torch.utils.data import TensorDataset, DataLoader
from torch.optim import SGD


X = torch.tensor([[1.0, 2.0], [2.0, 3.0], [3.0, 4.0]]) #required_grad = True is not required here as model itself initializer gradients
y_true = torch.tensor([[5.0], [8.0], [11.0]])

#dataset and loader are formed to perform minibatch
dataset = TensorDataset(X,y_true)
loader = DataLoader(dataset, batch_size = 2)
print('input tensor X is: ',X)

#setup model and required loss functions
model = Linear(in_features = 2, out_features=1)
loss = MSELoss()
optimizer = SGD(model.parameters(), lr = 0.01)


print('\n')
print('\n')


#initialize standard training loop with learning rate 0.01
for epoch in range(1,51):
    print('epoch iteration number : ', epoch)
    print('model weights: ', model.weight)
    
    for batch_X,batch_y in loader:
        #use model to predict
        y_pred = model(batch_X)

        #calculate the loss made in prediction
        mean_squared_error = loss(y_pred, batch_y)
    
        #reset the gradients so that they dont add up from previous epoch
        optimizer.zero_grad()
        
        #backpropagation
        mean_squared_error.backward()

        #adjust model weights to that model can predict better the next time.
        optimizer.step()
        print('y_pred is: ', y_pred)
    print(f'mean_squared_error for epoch number {epoch} is :', mean_squared_error)
    print('optimzed weights:', model.weight)
    print('\n')




input tensor X is:  tensor([[1., 2.],
        [2., 3.],
        [3., 4.]])




epoch iteration number :  1
model weights:  Parameter containing:
tensor([[-0.4447, -0.0329]], requires_grad=True)
y_pred is:  tensor([[-0.3161],
        [-0.7936]], grad_fn=<AddmmBackward0>)
y_pred is:  tensor([[1.0375]], grad_fn=<AddmmBackward0>)
mean_squared_error for epoch number 1 is : tensor(99.2509, grad_fn=<MseLossBackward0>)
optimzed weights: Parameter containing:
tensor([[0.3821, 1.1343]], requires_grad=True)


epoch iteration number :  2
model weights:  Parameter containing:
tensor([[0.3821, 1.1343]], requires_grad=True)
y_pred is:  tensor([[3.1853],
        [4.7017]], grad_fn=<AddmmBackward0>)
y_pred is:  tensor([[7.0625]], grad_fn=<AddmmBackward0>)
mean_squared_error for epoch number 2 is : tensor(15.5042, grad_fn=<MseLossBackward0>)
optimzed weights: Parameter containing:
tensor([[0.7025, 1.5845]], requires_grad=True)


epoch iteration number :  3
model weights:  Parameter containing:
tensor([[