In [ ]:
# 6: Training on a "Mini-Batch"The Concept: In the real world, we don't train on one row of data at a time. 
# we use a "batch."The Task: 
# 1. Create a dataset X with 3 rows of data: [[1.0, 2.0], [2.0, 3.0], [3.0, 4.0]].
# 2. Create $Y_{true}$ with 3 targets: [[5.0], [8.0], [11.0]].
# 3. Train your nn.Linear(2, 1) model for 50 epochs.
# Practical Goal: Observe how nn.MSELoss automatically calculates the average error across all 3 rows.

#import necessary libraries 
import torch
from torch.nn import Linear, MSELoss
from torch.utils.data import TensorDataset, DataLoader
from torch.optim import SGD


X = torch.tensor([[1.0, 2.0], [2.0, 3.0], [3.0, 4.0]]) #required_grad = True is not required here as model itself initializer gradients
y_true = torch.tensor([[5.0], [8.0], [11.0]])

#dataset and loader are formed to perform minibatch
dataset = TensorDataset(X,y_true)
loader = DataLoader(dataset, batch_size = 2)
print('input tensor X is: ',X)

#setup model and required loss functions
model = Linear(in_features = 2, out_features=1)
loss = MSELoss()
optimizer = SGD(model.parameters(), lr = 0.01)

print('\n')
print('\n')


#initialize standard training loop with learning rate 0.01
for epoch in range(1,51):
    print('epoch iteration number : ', epoch)
    print('model weights: ', model.weight)
    
    for batch_X,batch_y in loader:
        #use model to predict
        y_pred = model(batch_X)

        #calculate the loss made in prediction
        mean_squared_error = loss(y_pred, batch_y)
    
        #reset the gradients so that they dont add up from previous epoch
        optimizer.zero_grad()
        
        #backpropagation
        mean_squared_error.backward()

        #adjust model weights to that model can predict better the next time.
        optimizer.step()
        print('y_pred is: ', y_pred)
    print(f'mean_squared_error for epoch number {epoch} is :', mean_squared_error)
    print('optimzed weights:', model.weight)
    print('\n')




input tensor X is:  tensor([[1., 2.],
        [2., 3.],
        [3., 4.]])




epoch iteration number :  1
model weights:  Parameter containing:
tensor([[-0.4447, -0.0329]], requires_grad=True)
y_pred is:  tensor([[-0.3161],
        [-0.7936]], grad_fn=<AddmmBackward0>)
y_pred is:  tensor([[1.0375]], grad_fn=<AddmmBackward0>)
mean_squared_error for epoch number 1 is : tensor(99.2509, grad_fn=<MseLossBackward0>)
optimzed weights: Parameter containing:
tensor([[0.3821, 1.1343]], requires_grad=True)


epoch iteration number :  2
model weights:  Parameter containing:
tensor([[0.3821, 1.1343]], requires_grad=True)
y_pred is:  tensor([[3.1853],
        [4.7017]], grad_fn=<AddmmBackward0>)
y_pred is:  tensor([[7.0625]], grad_fn=<AddmmBackward0>)
mean_squared_error for epoch number 2 is : tensor(15.5042, grad_fn=<MseLossBackward0>)
optimzed weights: Parameter containing:
tensor([[0.7025, 1.5845]], requires_grad=True)


epoch iteration number :  3
model weights:  Parameter containing:
tensor([[

In [20]:
# 7: The "Vanishing Gradient" Sabotage
# The Concept: If your Learning Rate is too small, or your inputs are massive, gradients can become tiny.
# The Task: 
# 1. Use the same code from Question 5, but change your Learning Rate to something extremely small: lr = 1e-10.
# 2. Run it for 20 epochs.
# 3. Print the model.weight.grad in each loop.

# Practical Goal: See what happens when the gradient exists, but the "step" is so small the weights barely move. How many epochs would it take to actually learn at this speed?



#import necessary libraries 
import torch
from torch.nn import Linear, MSELoss
from torch.utils.data import TensorDataset, DataLoader
from torch.optim import SGD


X = torch.tensor([[1.0, 2.0], [2.0, 3.0], [3.0, 4.0]]) #required_grad = True is not required here as model itself initializer gradients
y_true = torch.tensor([[5.0], [8.0], [11.0]])

#dataset and loader are formed to perform minibatch
dataset = TensorDataset(X,y_true)
loader = DataLoader(dataset, batch_size = 2)
print('input tensor X is: ',X)

#setup model and required loss functions
model = Linear(in_features = 2, out_features=1)
loss = MSELoss()
optimizer = SGD(model.parameters(), lr = 1e-10)

print('\n')
print('\n')


#initialize standard training loop with learning rate 0.01
for epoch in range(1,21):
    print('epoch iteration number : ', epoch)
    print('model weights: ', model.weight)
    
    for batch_X,batch_y in loader:
        #use model to predict
        y_pred = model(batch_X)

        #calculate the loss made in prediction
        mean_squared_error = loss(y_pred, batch_y)
    
        #reset the gradients so that they dont add up from previous epoch
        optimizer.zero_grad()
        
        #backpropagation
        mean_squared_error.backward()

        #adjust model weights to that model can predict better the next time.
        optimizer.step()
        print('y_pred is: ', y_pred)
    print(f'mean_squared_error for epoch number {epoch} is: ', mean_squared_error)
    print('optimzed weights: ', model.weight)
    print('model weight gradient: ', model.weight.grad)
    print('\n')

input tensor X is:  tensor([[1., 2.],
        [2., 3.],
        [3., 4.]])




epoch iteration number :  1
model weights:  Parameter containing:
tensor([[-0.1714,  0.6493]], requires_grad=True)
y_pred is:  tensor([[1.2953],
        [1.7733]], grad_fn=<AddmmBackward0>)
y_pred is:  tensor([[2.2512]], grad_fn=<AddmmBackward0>)
mean_squared_error for epoch number 1 is:  tensor(76.5419, grad_fn=<MseLossBackward0>)
optimzed weights:  Parameter containing:
tensor([[-0.1714,  0.6493]], requires_grad=True)
model weight gradient:  tensor([[-52.4929, -69.9906]])


epoch iteration number :  2
model weights:  Parameter containing:
tensor([[-0.1714,  0.6493]], requires_grad=True)
y_pred is:  tensor([[1.2953],
        [1.7733]], grad_fn=<AddmmBackward0>)
y_pred is:  tensor([[2.2512]], grad_fn=<AddmmBackward0>)
mean_squared_error for epoch number 2 is:  tensor(76.5419, grad_fn=<MseLossBackward0>)
optimzed weights:  Parameter containing:
tensor([[-0.1714,  0.6493]], requires_grad=True)
model weight gra

In [ ]:
# : Introducing "Non-Linearity" (ReLU)The Concept: nn.Linear only learns straight lines. 
# To learn complex patterns, we add an "Activation Function" like ReLU ($f(x) = \max(0, x)$).
# The Task: 
# 1. Define a manual ReLU: y_pred = torch.relu(model(X)).
# 2. Use an input $X = [-10.0, -5.0]$ and a target $Y_{true} = [0.0]$.
# 3. If the model predicts a negative number, ReLU will turn it into $0$.
# Practical Goal: Look at the gradients when the output is blocked by ReLU. If the output is $0$, what happens to the gradient during .backward()?


import torch
from torch.nn import Linear

X = torch.tensor([-10.0, -5.0])
y_true = torch.tensor([0.0])

model = Linear(in_features=2, out_features=1)
y_pred = torch.relu(model(X))

print('y_pred is: ', y_pred)

print('model weight before backward propagation: ', model.weight)
print('model weight gradient before backward propagation: ', model.weight.grad)
print('\n')

y_pred.backward()

print('model weight before backward propagation: ', model.weight)
print('model weight gradient before backward propagation: ', model.weight.grad)

#when the output was non zero, the gradients got equal to the input itself as given in the example below, when the output was zero the gradients were also zero(Also show in example).

#non zero example
# y_pred is:  tensor([4.8153], grad_fn=<ReluBackward0>)
# model weight before backward propagation:  Parameter containing:
# tensor([[-0.3609, -0.1066]], requires_grad=True)
# model weight gradient before backward propagation:  None

# model weight before backward propagation:  Parameter containing:
# tensor([[-0.3609, -0.1066]], requires_grad=True)
# model weight gradient before backward propagation:  tensor([[-10.,  -5.]])

#zero example
# y_pred is:  tensor([0.], grad_fn=<ReluBackward0>)
# model weight before backward propagation:  Parameter containing:
# tensor([[0.6244, 0.4971]], requires_grad=True)
# model weight gradient before backward propagation:  None


# model weight before backward propagation:  Parameter containing:
# tensor([[0.6244, 0.4971]], requires_grad=True)
# model weight gradient before backward propagation:  tensor([[0., 0.]])

y_pred is:  tensor([0.], grad_fn=<ReluBackward0>)
model weight before backward propagation:  Parameter containing:
tensor([[0.6244, 0.4971]], requires_grad=True)
model weight gradient before backward propagation:  None


model weight before backward propagation:  Parameter containing:
tensor([[0.6244, 0.4971]], requires_grad=True)
model weight gradient before backward propagation:  tensor([[0., 0.]])


In [16]:
# 9: Binary Classification (Cross Entropy)The Concept: Not everything is a regression (predicting a price). Sometimes we predict "Yes" (1) or "No" (0). For this, we use nn.BCEWithLogitsLoss.
# The Task: 
# 1. Change your $Y_{true}$ to torch.tensor([[1.0]]).
# 2. Change your loss function to criterion = nn.BCEWithLogitsLoss().
# 3. Run the training loop for 20 epochs.
# Practical Goal: Notice how the loss behaves differently compared to MSE.


import torch
from torch.nn import BCEWithLogitsLoss, Linear
from torch.optim import SGD
from colorama import Fore,Style

X = torch.tensor([-10.0, -5.0])
y_true = torch.tensor([1.0])

model = Linear(in_features = 2, out_features=1)
loss = BCEWithLogitsLoss()
optimizer = SGD(model.parameters(), lr = 0.01)


for epoch in range(0,20):
    print(f'iteration for epoch number: ', epoch)
    optimizer.zero_grad() 

    y_pred = model(X)
    error = loss(y_pred, y_true)
    print(Fore.GREEN + 'y_pred is: ', y_pred)
    print(Style.RESET_ALL)
    print('error is: ', error)
    print(Fore.GREEN + 'model weights: ', model.weight)
    print(Style.RESET_ALL)

    error.backward()
    optimizer.step()
    print('model weight gradient: ', model.weight.grad)

    print(Fore.GREEN + 'optimzed model weights: ', model.weight)
    print(Style.RESET_ALL)

    print('\n')



iteration for epoch number:  0
y_pred is:  tensor([-6.8026], grad_fn=<ViewBackward0>)

error is:  tensor(6.8037, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
model weights:  Parameter containing:
tensor([[0.5901, 0.1311]], requires_grad=True)

model weight gradient:  tensor([[9.9889, 4.9945]])
optimzed model weights:  Parameter containing:
tensor([[0.4902, 0.0812]], requires_grad=True)



iteration for epoch number:  1
y_pred is:  tensor([-5.5440], grad_fn=<ViewBackward0>)

error is:  tensor(5.5479, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
model weights:  Parameter containing:
tensor([[0.4902, 0.0812]], requires_grad=True)

model weight gradient:  tensor([[9.9610, 4.9805]])
optimzed model weights:  Parameter containing:
tensor([[0.3906, 0.0313]], requires_grad=True)



iteration for epoch number:  2
y_pred is:  tensor([-4.2889], grad_fn=<ViewBackward0>)

error is:  tensor(4.3025, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
model weights:  Parameter containing:
tensor([

In [ ]:
# 10: Debugging "Exploding Gradients"
# The Concept: If the Learning Rate is too high, the weights "explode" to Inf or NaN (Not a Number).
# The Task: 
# 1. Take your working code from Question 5.
# 2. Set lr = 100.0.
# 3. Run the loop for just 5 iterations and print the loss.

# Practical Goal: Learn to recognize the NaN error—the most common "heart attack" a neural network suffers.

X = torch.tensor([2.0, 3.0])
W = torch.randn(2, 1, requires_grad=True) # Random weights
b = torch.randn(1, requires_grad=True)    # Random bias
y_true = torch.tensor([-5.0])